add upload file + style input file
vravanel/luxelair pull request #15
Opened 2024-02-06 15:34 UTC by vravanel

2024-02-07 10:48 UTC, arnaudrenaud requested changes

2024-02-07 10:48 UTC, arnaudrenaud commented on file-hosting/src/index.js
Ce fichier est une version compilée du fichier `index.ts`. Il doit être retiré de Git.

2024-02-07 10:48 UTC, arnaudrenaud commented on web-app/src/components/CreateAdComponent.tsx
> +      console.log(error);
Logger une erreur interceptée est inutile, c'est déjà le comportement par défaut.

2024-02-08 13:20 UTC, koukabel approved these changes

2024-02-08 13:21 UTC, merged